/* 
 * File:   frame_class_sub_decl.h
 * Author: markw
 *
 * Created on November 9,\ 2020,\ 11:32 AM
 */
#define FRAME_CLASS_SUB_VALUES \
    DECL_ENUM_ELEMENT(BLUEROV1),\
    DECL_ENUM_ELEMENT(VECTORED),\
    DECL_ENUM_ELEMENT(VECTORED_6DOF),\
    DECL_ENUM_ELEMENT(VECTORED_6DOF_90DEG),\
    DECL_ENUM_ELEMENT(SIMPLEROV_3),\
    DECL_ENUM_ELEMENT(SIMPLEROV_4),\
    DECL_ENUM_ELEMENT(SIMPLEROV_5),\
    DECL_ENUM_ELEMENT(CUSTOM)
